source("./code/functions.R")

board_matrix <- function(squares_table) {
    # Function takes a table of squares with number of moves for each square.
    # For example, it could be one element of "squares" list, generated by
    #  function "popular_squares()"
    
    # Matrix, representing an empty board.
    # Column names are letters, row names are characters of numbers.
    # Looks like this:
    # [[1]]
    #   a b c d e f g h
    # 8 0 0 0 0 0 0 0 0
    # 7 0 0 0 0 0 0 0 0
    # 6 0 0 0 0 0 0 0 0
    # 5 0 0 0 0 0 0 0 0
    # 4 0 0 0 0 0 0 0 0
    # 3 0 0 0 0 0 0 0 0
    # 2 0 0 0 0 0 0 0 0
    # 1 0 0 0 0 0 0 0 0
    board <- matrix(0, 8, 8, dimnames = list(as.character(8:1), letters[1:8]))
    
    for (square in names(squares_table)) {
        file <- substr(square, 1, 1)
        rank <- substr(square, 2, 2)
        board[rank, file] <- squares_table[square]
    }
        
    board    

}
